In [1]:
#Importamos librerias
import numpy as np

## Factorización **ALU**
- Una matriz $L \in \mathbb{R}^{m×n}$ es **triangular inferior** si sus coeficientes satisfacen $l_{ij} = 0$ para $i < j$.

- Una matriz $U \in \mathbb{R}^{m×n}$ es **triangular superior** si sus coeficientes satisfacen $u_{ij} = 0$ para $i > j$.

### Buscamos factorizar la matriz de coeficientes A en la multiplicación de dos matrices trianguales L y U. Esto se basa en los siguientes tres hechos

* 1.- Sea $L_{ij}(−c)$ la matriz triangular inferior la cual tiene coeficientes no-cero en su diagonal y la posición $(i, j)$. La diagonal $son 1’s$ y en la posición $(i, j)$ es $(−c)$. Entonces $L_{ij}(−c) \cdot A$ representa la operación fila “restar la fila j multiplicada por $−c$ a la fila $i$ ".

__Ejemplo:__

$$
    A = 
        \begin{bmatrix}
            a_{11} &  a_{12}\\
            a_{21} &  a_{22}
        \end{bmatrix},
    L_{21}(-c) \cdot A = 
        \begin{bmatrix}
             1 &  0\\
            -c &  1
        \end{bmatrix}
        \begin{bmatrix}
            a_{11} &  a_{12}\\
            a_{21} &  a_{22}
        \end{bmatrix} = 
        \begin{bmatrix}
            a_{11} &  a_{12}\\
            a_{21}-ca_{11} &  a_{22}-ca_{21}
        \end{bmatrix}
$$

In [31]:
c = 2

A = np.array([
    [5, 4],
    [3, 2]
])

L_21 = np.array([
    [ 1, 0],
    [-c, 1]
])

print('A\n', A)
print('\nL_21\n', L_21)
print('\nL_21 * A\n', L_21@A)

A
 [[5 4]
 [3 2]]

L_21
 [[ 1  0]
 [-2  1]]

L_21 * A
 [[ 5  4]
 [-7 -6]]


* 2.- $L_{ij}(−c)^{−1} = L_{ij}(c)$ , recuerde $A \cdot A^{−1} = I$

__Ejemplo:__

$$
    \begin{bmatrix}
         1 &  0\\
        -c &  1
    \end{bmatrix}^{-1}
    \begin{bmatrix}
         1 &  0\\
        -c &  1
    \end{bmatrix}
    =
    \begin{bmatrix}
         1 &  0\\
         0 &  1
    \end{bmatrix}
$$

$$
    \begin{bmatrix}
         1 &  0\\
         c &  1
    \end{bmatrix}
    \begin{bmatrix}
         1 &  0\\
        -c &  1
    \end{bmatrix}
    =
    \begin{bmatrix}
         1   &  0\\
         c-c &  1
    \end{bmatrix}
    =
    \begin{bmatrix}
         1 &  0\\
         0 &  1
    \end{bmatrix}
$$

In [36]:
c = 3
L_ij = np.array([
    [ 1, 0],
    [-c, 1]
])

L_ij_i = np.linalg.inv(L_ij)

print('L_ij\n', L_ij)
print('\nL_ij_i\n', L_ij_i)
print('\nL_ij * L_ij_i\n', L_ij@L_ij_i)

L_ij
 [[ 1  0]
 [-3  1]]

L_ij_i
 [[ 1. -0.]
 [ 3.  1.]]

L_ij * L_ij_i
 [[1. 0.]
 [0. 1.]]


* 3.- La siguiente ecuación matricial es cierta:

$$
    \begin{bmatrix}
        1 & 0 & 0\\
        c_1 & 1 & 0\\
        0 & 0 & 1
    \end{bmatrix}
     \begin{bmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        c_2 & 0 & 1
    \end{bmatrix}
     \begin{bmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        0 & c_3 & 1
    \end{bmatrix}
    =
     \begin{bmatrix}
        1 & 0 & 0\\
        c_1 & 1 & 0\\
        c_2 & c_3 & 1
    \end{bmatrix}
$$

__Ejemplo:__

\begin{equation}
    \begin{bmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        0 & \frac{7}{3} & 1
    \end{bmatrix}
     \begin{bmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        3 & 0 & 1
    \end{bmatrix}
     \begin{bmatrix}
        1 & 0 & 0\\
        -2 & 1 & 0\\
        0 & 0 & 1
    \end{bmatrix}
    \begin{bmatrix}
        1 & 2 & -1\\
        2 & 1 & -2\\
        -3 & 1 & 1
    \end{bmatrix}=
     \begin{bmatrix}
        1 & 2 & -1\\
        0 & -3 & 0\\
        0 & 0 & -2
    \end{bmatrix} = U
\end{equation}
&nbsp;$L_3$  $L_2$  $L_1$   $\leftarrow$ fact 1  $\uparrow A$



Es decir $L_1L_2L_1A=U$

\begin{align}
    A &= L_1^{-1}L_2^{-1}L_1^{-1}U && \leftarrow \text{fact2}\\
      &= \tilde{L_1}\tilde{L_2}\tilde{L_3}U && \leftarrow \text{fact3}\\
      &= LU
\end{align}

In [2]:
L_3 = np.array([
    [1,0  ,0],
    [0,1  ,0],
    [0,7/3,1]
])

L_2 = np.array([
    [1,0,0],
    [0,1,0],
    [3,0,1]
])

L_1 = np.array([
    [1 ,0,0],
    [-2,1,0],
    [0 ,0,1]
])

A = np.array([
    [ 1, 2,-1],
    [ 2, 1,-2],
    [-3, 1, 1]
])

U = L_3@L_2@L_1@A

L = np.linalg.inv(L_1)@np.linalg.inv(L_2)@np.linalg.inv(L_3)

print("A\n", A)
print("\nL\n", L)
print("\nU\n", np.round(U))
print("\nLU\n", np.round(L@U))
print("\nA == LU\n", np.round(L@U) == A)

A
 [[ 1  2 -1]
 [ 2  1 -2]
 [-3  1  1]]

L
 [[ 1.          0.          0.        ]
 [ 2.          1.          0.        ]
 [-3.         -2.33333333  1.        ]]

U
 [[ 1.  2. -1.]
 [ 0. -3.  0.]
 [ 0. -0. -2.]]

LU
 [[ 1.  2. -1.]
 [ 2.  1. -2.]
 [-3.  1.  1.]]

A == LU
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
L_3 = np.array([
    [1,0  ,0],
    [0,1  ,0],
    [0,-4,1]
])

L_2 = np.array([
    [1,0,0],
    [0,1,0],
    [-4,0,1]
])

L_1 = np.array([
    [1 ,0,0],
    [-4,1,0],
    [0 ,0,1]
])

A = np.array([
    [ 1, 2,2],
    [ 4, 1,2],
    [ 4, 4,1]
])

U = L_3@L_2@L_1@A

L = np.linalg.inv(L_1)@np.linalg.inv(L_2)@np.linalg.inv(L_3)

print("A\n", A)
print("\nL\n", L)
print("\nU\n", np.round(U))
print("\nLU\n", np.round(L@U))
print("\nA == LU\n", np.round(L@U) == A)

A
 [[1 2 2]
 [4 1 2]
 [4 4 1]]

L
 [[ 1.  0.  0.]
 [ 4.  1.  0.]
 [20.  4.  1.]]

U
 [[ 1  2  2]
 [ 0 -7 -6]
 [ 0 24 17]]

LU
 [[ 1.  2.  2.]
 [ 4.  1.  2.]
 [20. 36. 33.]]

A == LU
 [[ True  True  True]
 [ True  True  True]
 [False False False]]
