## Gradiente descendente

Buscamos minimazar una función cuadrática convexa _$f$_ al movernos en la dirección de máximo decrecimiento, la cual viene dada por $\nabla f$.

Tras encontrar un mínimo, debemos repetir este proceso.

In [5]:
import numpy as np

In [ ]:
def grad_dec(A, b, tol=1e-10):
    xs = [np.zeros(b.shape[0])]
    r_ks = []
    a_ks = []
    i = 0
    while i>=0:
        r_k = b-A@xs[i]
        a_k = (r_k.T@r_k)/(r_k.T@A@r_k)
        a_ks.append(a_k)
        r_ks.append(r_k)        
        xs.append(np.array(xs[i]+a_k*r_k))
        if np.linalg.norm(r_ks[i]) < tol:
            break
        i += 1
    return np.array(xs), np.array(a_ks), np.array(r_ks)

Este método converge a la solución de $Ax=b$ para toda matriz $A$ que sea simétrica y definida positiva.

### Gradiente Conjugado

Método utilizado para resolver sistemas de ecuaciones lineales($Ax=b$), donde $A$ es una matriz simétrica definida positiva.

Buscamos construir la solución $x$ como la combinación lineal de vectores $\mathbb{R}^n$ linealmente independientes.

$$
    x = x_0 + \sum_{i=0}^{n-1}\alpha_i d_i
$$

In [32]:
np.random.seed(123)
n = 2
A = np.random.rand(n, n)
A = A@A.T + np.eye(n)
b = np.random.rand(n)
A, b

(array([[1.56694505, 0.31574789],
        [0.31574789, 1.35540956]]),
 array([0.71946897, 0.42310646]))

In [81]:
x, a, r = grad_dec(A, b)
x

array([[0.        , 0.        ],
       [0.40226904, 0.23656702],
       [0.41500462, 0.21491087],
       [0.41574371, 0.21534552],
       [0.41576711, 0.21530573],
       [0.41576847, 0.21530653],
       [0.41576851, 0.21530646],
       [0.41576851, 0.21530646],
       [0.41576851, 0.21530646],
       [0.41576851, 0.21530646]])

In [52]:
x1, r1 = gradientDescent(A, b)
x1

array([[0.        , 0.        ],
       [0.40226904, 0.23656702],
       [0.41500462, 0.21491087],
       [0.41574371, 0.21534552],
       [0.41576711, 0.21530573],
       [0.41576847, 0.21530653],
       [0.41576851, 0.21530646],
       [0.41576851, 0.21530646],
       [0.41576851, 0.21530646]])

In [54]:
x_real = np.linalg.solve(A, b)
x_real

array([0.41576851, 0.21530646])

In [83]:
np.equal(x[:9], x1)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])