In [18]:
import numpy as np

In [19]:
a = np.array([(1,2), (2,3), (3,4)])
a.shape

(3, 2)

In [20]:
p = np.poly1d([1, 3, 1, 0, 4])

print(p)
print(p.deriv(1))

   4     3     2
1 x + 3 x + 1 x + 4
   3     2
4 x + 9 x + 2 x


In [21]:
a = np.array([1,2,3,4])
a[::-1]

array([4, 3, 2, 1])

In [22]:
len(a)

4

In [23]:
m = np.zeros((10,10))

In [24]:
for i in range(10):
    for j in range(10):
        m[i][j] = j+1+10*i
m

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [25]:
5//2

2

In [26]:
A = np.array([
    [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0],
    [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,1,2,3,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0],
    [0,1,2,3,0,1,2,3,0,1,2,3,0,1,2,3],
    [0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0],
    [0,0,0,0,1,0,0,0,2,0,0,0,3,0,0,0],
    [0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3],
    [0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,1,2,3,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,1,0,0,0,2,0,0,0,3,0,0],
    [0,0,0,0,0,1,2,3,0,2,4,6,0,3,6,9]
])
A[17][17]

IndexError: index 17 is out of bounds for axis 0 with size 16

In [27]:
old_set = [1,2,3]
new_set = [2,3,4]

np.mean( np.array([ old_set, new_set ]), axis=0 )

array([1.5, 2.5, 3.5])

In [37]:
arr = np.array([[1,2,3],[4,5,6]])
a = np.hstack((arr, np.tile(arr[:, [-1]], 1)))
a = np.vstack([a, a[1]])

In [35]:
np.zeros((2,2,3))[:,:,-1]

array([[0., 0.],
       [0., 0.]])

In [36]:
np.repeat(a, [1]*(a.shape[1]-1) +[3], axis=1)

array([[1, 2, 3, 3, 3, 3],
       [4, 5, 6, 6, 6, 6],
       [4, 5, 6, 6, 6, 6]])

In [88]:
arr = np.array([[[ 25.,  60.,  79.],
        [ 23.,  59.,  78.],
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 255.]],
               [[ 25.,  60.,  79.],
        [ 23.,  59.,  78.],
        [255., 255., 255.],
        [255., 255., 255.],
        [255., 255., 0.]]])

In [89]:
np.tile(arr[:,-1], 1)

array([[255., 255., 255.],
       [255., 255.,   0.]])

In [90]:
arr[-1]

array([[ 25.,  60.,  79.],
       [ 23.,  59.,  78.],
       [255., 255., 255.],
       [255., 255., 255.],
       [255., 255.,   0.]])

In [91]:
np.append(arr, arr[:][-1][-1], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 1 dimension(s)

In [102]:
aaa = np.ones(arr.shape[0])
aaa[-1] = 2
arr, np.repeat(arr, repeats = aaa.astype(int), axis=1)

ValueError: operands could not be broadcast together with shape (5,) (2,)

In [112]:
x = np.array([[0, 3, 4], [1, 2, 4], [3, 4, 5]]) 
x.shape

(3, 3)

In [2]:
10/4

2.5

In [59]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = a+1

In [60]:
a[0: 3]

array([1, 2, 3])

In [61]:
n = 105
np.floor(n/4)**2

676.0

In [70]:
np.floor(8/4).astype(int)**2

4

In [79]:
n = 13
int((n-1)/4)

3

In [65]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
int((8)/4)

2

In [80]:
def create_constraints(image):
    '''
    image: (array nxn) imagen que presenta ruido en sus datos
    
    return
    constraints: (list) lista de restricciones  
    '''
    n = image.shape[0]
    max_b = int((n-1)/4 - 1)
    constraints = []
    #'type': 'eq', 'fun': lambda a:  spline_evaluate(a[0:16], (4,4)) - spline_evaluate(a[16*max_b+16: max_b*16+32], (4,4))
    bloque = 0
    for i in range(n):
        if i%4==0 and i > 0 and i!=n-1:
            bloque += max_b+1
        if bloque < max_b:
            constraints.append({'type': 'eq', 'fun': lambda a:  spline_evaluate(a[bloque*16:bloque*16+16], (j,i)) - 
                                                                spline_evaluate(a[(bloque+max_b)*16: (bloque+max_b)*16+16], (j,i))})
        for j in range(n):
            if j>0 and j%4 == 0 and j!=n-1:
                bloque += 1
            if bloque < max_b:
                constraints.append({'type': 'eq', 'fun': lambda a:  spline_evaluate(a[bloque*16:bloque*16+16], (j,i)) - 
                                                                        spline_evaluate(a[(bloque+1)*16: (bloque+1)*16+16], (j,i))})
        bloque -= max_b
    return constraints
img_noise = np.array([[0.8, 0.8, 0.8, 0.8, 1.2, 1.2, 1.2, 1.2, 1.2],
                      [0.8, 1.2, 0.8, 1.2, 0.8, 1.2, 0.8, 0.8, 0.8],
                      [1.2, 1.2, 0.8, 1.2, 0.8, 0.8, 0.8, 0.8, 0.8],
                      [1.2, 0.8, 0.8, 1.2, 1.2, 0.8, 0.8, 0.8, 0.8],
                      [0.8, 1.2, 0.8, 0.8, 1.2, 0.8, 1.2, 0.8, 0.8],
                      [0.8, 0.8, 0.8, 0.8, 1.2, 0.8, 1.2, 1.2, 0.8],
                      [1.2, 1.2, 0.8, 0.8, 1.2, 0.8, 0.8, 0.8, 1.2],
                      [0.8, 1.2, 0.8, 0.8, 1.2, 0.8, 1.2, 0.8, 0.8],
                      [0.8, 0.8, 1.2, 0.8, 0.8, 0.8, 1.2, 0.8, 0.8]])
len(create_constraints(img_noise))

20

In [81]:
for i in range(0,4,2):
    print(i)

0
2


In [82]:
pr = lambda x: print(x[1])
pr(a)

2


In [6]:
a = [[1+j for i in range(16)] for j in range(1)]
a

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [7]:
a[0]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [8]:
import numpy as np

In [10]:
b = np.array(a[0])

b.reshape(1, 16)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [27]:
cons = []
bloque = 0
cons.append({'fun': lambda x, bloque=bloque: np.cos(int(str(bloque))*x)})
print(cons[0]['fun'](1))
bloque = 1
print(cons[0]['fun'](1))

1.0
1.0
