In [1]:
import numpy as np
from scipy.linalg import toeplitz

In [21]:
a = np.array([1,2,3,0,0,0])
b = toeplitz(a)
m = 3
b

array([[1, 2, 3, 0, 0, 0],
       [2, 1, 2, 3, 0, 0],
       [3, 2, 1, 2, 3, 0],
       [0, 3, 2, 1, 2, 3],
       [0, 0, 3, 2, 1, 2],
       [0, 0, 0, 3, 2, 1]])

In [70]:
b = toeplitz(a)
n = b.shape[0]-1
for i in range(n):
    for k in range(i+1, n):
        mult = b[k][i]/b[i][i]
        for j in range(i, i+m):
            b[k][j] = b[k][j] - mult*b[i][j]
        print(mult)
b

2.0
3.0
0.0
0.0
1.3333333333333333
-1.0
-0.0
1.0
-1.5
-0.16666666666666666


array([[ 1,  2,  3,  0,  0,  0],
       [ 0, -3, -4,  3,  0,  0],
       [ 0,  0, -2, -2,  3,  0],
       [ 0,  0,  0,  6, -1,  3],
       [ 0,  0,  0,  0,  4,  2],
       [ 0,  0,  0,  3,  2,  1]])

In [84]:
from scipy import linalg as spla
b = np.identity(3)
a = np.array([
    [16,-8,-4],
    [-8,29,12],
    [-4,12,41]
])
R = np.linalg.cholesky(a)
ri = spla.solve_triangular(R, b, lower=True)
np.linalg.inv(R), ri

(array([[ 0.25      ,  0.        ,  0.        ],
        [ 0.1       ,  0.2       ,  0.        ],
        [ 0.00833333, -0.06666667,  0.16666667]]),
 array([[ 0.25      ,  0.        ,  0.        ],
        [ 0.1       ,  0.2       ,  0.        ],
        [ 0.00833333, -0.06666667,  0.16666667]]))

In [86]:
ri.T@ri, np.linalg.inv(a)

(array([[ 0.07256944,  0.01944444,  0.00138889],
        [ 0.01944444,  0.04444444, -0.01111111],
        [ 0.00138889, -0.01111111,  0.02777778]]),
 array([[ 0.07256944,  0.01944444,  0.00138889],
        [ 0.01944444,  0.04444444, -0.01111111],
        [ 0.00138889, -0.01111111,  0.02777778]]))

\begin{align}
    Total &= \sum_{j=1}^{n}\sum_{i=j+1}^{n}(1 + \sum_{k=j}^{j+m} 2)\\
          &= \sum_{j=1}^{n}\sum_{i=j+1}^{n}(1 + 2\frac{m}{2}(2j+m))\\
          &= \sum_{j=1}^{n}\sum_{i=j+1}^{n}(1 + 2mj+m^2)\\
          &= \sum_{j=1}^{n}(1 + 2mj+m^2)\sum_{i=j+1}^{n}1\\
          &= \sum_{j=1}^{n}(1 + 2mj+m^2)\sum_{h=1}^{n-j}1\\
          &= \sum_{j=1}^{n}(1 + 2mj+m^2)(n-j)\\
          &= \sum_{j=1}^{n}(n + 2mjn + m^2n)-(j + 2mj^2+jm^2)\\
          &= \sum_{j=1}^{n}(n + 2mjn + m^2n - j - 2mj^2 - jm^2)\\
          &= \sum_{j=1}^{n} mn^2 + n - 2mj^2 +j(2mn-m^2-1)\\
          &= \sum_{j=1}^{n}mn^2 + \sum_{j=1}^{n}n - 2m\sum_{j=1}^{n}j^2 +(2mn-m^2-1)\sum_{j=1}^{n}j\\
          &= mn^3 + n^2 - 2m\frac{n(n+1)(2n+1)}{6} + (2mn-m^2-1)\frac{n(n+1)}{2}\\
          &= mn^3 + n^2 - \frac{2mn^3+3mn^2+mn}{3} + (2mn-m^2-1)\frac{n^2+n}{2}\\
          &= \frac{4}{3}mn^3 - \frac{1}{2}m^2n^2 - \frac{1}{2}m^2n - \frac{1}{2}mn - \frac{1}{2}n^2 - \frac{1}{2}n
\end{align}